AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  address-auto-complete

  Sample SAM Template for address-auto-complete

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
  Api:
    Cors: "'*'"
Resources:
  AddressLookupFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Events:
        AddressLookup:
          Type: Api
          Properties:
            Path: /address
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./address-lookup
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddressLookupApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AddressLookupFunctionFunction:
    Description: "AddressLookupFunction Lambda Function ARN"
    Value: !GetAtt AddressLookupFunction.Arn
  AddressLookupFunctionIamRole:
    Description: "Implicit IAM Role created for AddressLookupFunction function"
    Value: !GetAtt AddressLookupFunctionRole.Arn
